send_lsl_triggers: False
reaction_keys: {"match": left, "no match": right}

training: True # True or False depends on if you want to run training
training_trials: [{ "load": 3, "hemifield": left, "match": True, "n": 1 },
                  { "load": 6, "hemifield": left, "match": True, "n": 1 },
                  { "load": 3, "hemifield": right, "match": True, "n": 1 },
                  { "load": 6, "hemifield": right, "match": True, "n": 1 },
                  { "load": 3, "hemifield": left, "match": False, "n": 1 },
                  { "load": 6, "hemifield": left, "match": False, "n": 1 },
                  { "load": 3, "hemifield": right, "match": False, "n": 1 },
                  { "load": 6, "hemifield": right, "match": False, "n": 1 }]
training_time: 5 # 5
training_fixation_time: [1, 2] # [8, 12]
training_wait_time: [1, 2]

first_fixation: True # True or False depends on if you want to have special fixation at the start of the experiment
first_fixation_time: 20

experiment_trials: [{ "load": 3, "hemifield": left, "match": True, "n": 3 },
                  { "load": 4, "hemifield": left, "match": True, "n": 3 },
                  { "load": 5, "hemifield": left, "match": True, "n": 3 },
                  { "load": 6, "hemifield": left, "match": True, "n": 3 },
                  { "load": 7, "hemifield": left, "match": True, "n": 3 },
                  { "load": 8, "hemifield": left, "match": True, "n": 3 },
                  { "load": 3, "hemifield": right, "match": True, "n": 3 },
                  { "load": 4, "hemifield": right, "match": True, "n": 3 },
                  { "load": 5, "hemifield": right, "match": True, "n": 3 },
                  { "load": 6, "hemifield": right, "match": True, "n": 3 },
                  { "load": 7, "hemifield": right, "match": True, "n": 3 },
                  { "load": 8, "hemifield": right, "match": True, "n": 3 },
                  { "load": 3, "hemifield": left, "match": False, "n": 3 },
                  { "load": 4, "hemifield": left, "match": False, "n": 3 },
                  { "load": 5, "hemifield": left, "match": False, "n": 3 },
                  { "load": 6, "hemifield": left, "match": False, "n": 3 },
                  { "load": 7, "hemifield": left, "match": False, "n": 3 },
                  { "load": 8, "hemifield": left, "match": False, "n": 3 },
                  { "load": 3, "hemifield": right, "match": False, "n": 3 },
                  { "load": 4, "hemifield": right, "match": False, "n": 3 },
                  { "load": 5, "hemifield": right, "match": False, "n": 3 },
                  { "load": 6, "hemifield": right, "match": False, "n": 3 },
                  { "load": 7, "hemifield": right, "match": False, "n": 3 },
                  { "load": 8, "hemifield": right, "match": False, "n": 3 }]
experiment_time: 5 # 5
experiment_fixation_time: [1, 2] # [8, 12]
experiment_wait_time: [1, 2]

# ---------------------- feedback ---------------------- #
feedback: True
feedback_time: 2
feedback_correct: Poprawna odpowiedź
feedback_incorrect: Odpowiedź niepoprawna
feedback_no_ans: Nie udzieliłeś odpowiedzi
feedback_color: black
feedback_size: 20

# ----------------------- visual ----------------------- #
figures_shapes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25] # first value in file name in folder images
figures_colors: [1, 26, 13, 2, 9, 14, 10, 20, 3]

figure_central_pos: [0, 0]
figure_central_size: 60

figure_arc_radius0: 200 # distance to central point of figure arc
figure_arc_radius1: 200 # distance to strat/end point of figure arc
figure_arc_angle: 45 # arc angle
maximum_load: 8
figure_cluster_size: 40

stimulus_color: black
stimulus_size: 60

screen_color: grey
fixation_color: black
fixation_text: +
fixation_size: 60

text_size: 20
text_color: black

exit_key: f7