reaction_keys: {"match": left, "no match": right}


training: True # True or False depends on if you want to run training
training_trials: [{ "load": 3, "hemifield": left, "match": True, "n": 1 },
                  { "load": 6, "hemifield": left, "match": True, "n": 1 },
                  { "load": 3, "hemifield": right, "match": True, "n": 1 },
                  { "load": 6, "hemifield": right, "match": True, "n": 1 },
                  { "load": 3, "hemifield": left, "match": False, "n": 1 },
                  { "load": 6, "hemifield": left, "match": False, "n": 1 },
                  { "load": 3, "hemifield": right, "match": False, "n": 1 },
                  { "load": 6, "hemifield": right, "match": False, "n": 1 }]
training_time: 1 # 5
training_fixation_time: [0.5, 0.5] # [8, 12]

first_fixation: True # True or False depends on if you want to have special fixation at the start of the experiment
first_fixation_time: 20

experiment_trials: [{ "load": 3, "hemifield": left, "match": True, "n": 3 },
                  { "load": 4, "hemifield": left, "match": True, "n": 3 },
                  { "load": 5, "hemifield": left, "match": True, "n": 3 },
                  { "load": 6, "hemifield": left, "match": True, "n": 3 },
                  { "load": 7, "hemifield": left, "match": True, "n": 3 },
                  { "load": 8, "hemifield": left, "match": True, "n": 3 },
                  { "load": 3, "hemifield": right, "match": True, "n": 3 },
                  { "load": 4, "hemifield": right, "match": True, "n": 3 },
                  { "load": 5, "hemifield": right, "match": True, "n": 3 },
                  { "load": 6, "hemifield": right, "match": True, "n": 3 },
                  { "load": 7, "hemifield": right, "match": True, "n": 3 },
                  { "load": 8, "hemifield": right, "match": True, "n": 3 },
                  { "load": 3, "hemifield": left, "match": False, "n": 3 },
                  { "load": 4, "hemifield": left, "match": False, "n": 3 },
                  { "load": 5, "hemifield": left, "match": False, "n": 3 },
                  { "load": 6, "hemifield": left, "match": False, "n": 3 },
                  { "load": 7, "hemifield": left, "match": False, "n": 3 },
                  { "load": 8, "hemifield": left, "match": False, "n": 3 },
                  { "load": 3, "hemifield": right, "match": False, "n": 3 },
                  { "load": 4, "hemifield": right, "match": False, "n": 3 },
                  { "load": 5, "hemifield": right, "match": False, "n": 3 },
                  { "load": 6, "hemifield": right, "match": False, "n": 3 },
                  { "load": 7, "hemifield": right, "match": False, "n": 3 },
                  { "load": 8, "hemifield": right, "match": False, "n": 3 }]
experiment_time: 1 # 5
experiment_fixation_time: [0.5, 0.5] # [8, 12]


# ----------------------- visual ----------------------- #
figures_shapes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25] # first value in file name in folder images
figures_colors: [1, 26, 13, 2, 9, 14, 10, 20, 3]

figure_central_pos: [0, 0]
figure_central_size: 60

figure_cluster_radius: 150
figure_cluster_size: 40
cluster_angle: 90
maximum_load: 8

stimulus_color: black
stimulus_size: 60

screen_color: grey
fixation_color: black
fixation_text: +
fixation_size: 60

text_size: 20
text_color: black


exit_key: f7